package associacao;
//ASSOCIAÇÃO ESTRUTURAL - COMPOSIÇÃO "COM PARTE TODO":
public class Pessoa {
	
		Endereco endereco; //ENDEREÇO PERTENCE A PESSOA SE PESSOA DIEXA DE EXISTIR ENDEREÇO TBM DEIXARÁ. 
		                     //PESSOA É COMPOSTA PELO ENDEREÇO E ENDEREÇO SÓ PERTENCE A ESSA PESSOA, TEMOS UMA COMPOSIÇÃO.
}
